name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint  --filter=-legal --linelength=100 *.cpp

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror tshirtsn.cpp  tshirtsn_test.cpp -o tshirts.out
        bash .github/workflows/expectfail.sh ./tshirts.out

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror color_mapn.cpp  color_mapn_test.cpp -o misaligned.out
        bash .github/workflows/expectfail.sh ./misaligned.out

    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror weatherreportn.cpp weatherreportntest.cpp -o weatherreport.out
        bash .github/workflows/expectfail.sh ./weatherreport.out
