name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint  --filter=-legal --linelength=100 *.cpp

    - name: tshirts pass
      run: |
        g++ -Wall -Wextra -Werror tshirtsn.cpp  tshirtsn_test.cpp -o tshirts.out
      

    - name: misaligned pass
      run: |
        g++ -Wall -Wextra -Werror color_mapn.cpp  color_mapn_test.cpp -o misaligned.out
       

    - name: alerter pass
      run: |
        g++ -Wall -Wextra -Werror weatherreportn.cpp weatherreportntest.cpp -o weatherreport.out
        
